Add additional standards from Farama Handbook
Farama-Foundation/farama.org pull request #75
Opened 2023-04-14 23:03 UTC by elliottower

This adds additional standards from the Farama Handbook which were not transcribed in my previous PR.

2023-04-15 21:30 UTC, jkterry1 requested changes

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Do it right the first time.</b> We strive to design flexible APIs which can be maintained for many years to come. When bringing in outside projects, breaking changes may be requir
We want to _have_ flexible APIs, not design them, and we want them to be easy to use for years to come too. Also note that when a project comes in, breaking changes are worth doing to achieve this our view. Maybe call this "do it right once"?

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>APIs should be user-friendly and enforce correct usage.</b> New users should be able to easily use APIs correctly without needing to dig through source code."
And APIs should keep people from doing dumb things (e.g. the truncation issue)

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Use deprecation warnings whenever possible.</b> This gives users time to adapt their code and mitigates the severity of breaking changes. Releasing breaking changes without is str
We also want broken changes to give good error messages

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Include only environments which are scientifically important or widely used.</b> We value quality over quantity for environments. Toy environments which do not have scientific val
There's lots of toy environments that are important, and lots of non toy environments that aren't.

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Projects should look professional and highly polished.</b> This means having a comprehensive README and documentation site, with straightforward wording which makes sense to new u
Don't limit this to just the readme and doc site. This can also apply to rendering and things for environments too

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Rendering should be high-quality and consistent between environments.</b> We try to use Pygame for all 2D Python graphics, and create pixel art when native rendering does not exis
try to use -> usually use

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Limit projects to a single purpose.</b> Ideally, standard APIs, utilities, environments and datasets should be split into separate repositories. This makes maintenance more manage
"simplifies user experience."" something sounds wrong there

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Use semantic versioning.</b> We limit minor releases and patches to `0.0.x` version bumps, with `0.x.0` for standard releases. We reserve `x.0.0` versions for initial maturity rel
"significant API changes and/or major additional functionality. "

2023-04-15 21:30 UTC, jkterry1 commented on _data/project_standards.yml
> +        - name: "<b>Communicate clearly with the community about upcoming changes.</> This means including thorough release notes with specific instructions in the case of breaking changes, respondin
-talk about the importance of release notes telling people whats happening next
-roadmaps
-social media

2023-04-19 21:46 UTC, elliottower commented on _data/project_standards.yml
> +        - name: "<b>Do it right the first time.</b> We strive to design flexible APIs which can be maintained for many years to come. When bringing in outside projects, breaking changes may be requir
I changed this one to say "do it right the first time, and eliminate technical debt"

2023-04-19 21:47 UTC, elliottower commented on _data/project_standards.yml
> +        - name: "<b>APIs should be user-friendly and enforce correct usage.</b> New users should be able to easily use APIs correctly without needing to dig through source code."
What exactly do you mean by the truncation issue? I'm assuming this is to do with changing done to terminated/truncated but not sure exactly what issue users did previously (mistake an environment for being done when it was just truncated?)

2023-04-19 22:04 UTC, elliottower commented on _data/project_standards.yml
> +        - name: "<b>Include only environments which are scientifically important or widely used.</b> We value quality over quantity for environments. Toy environments which do not have scientific val
I clarified this as "Environments which are not commonly used and have limited scientific value should be removed, or included only in tutorials. Toy environments should be kept only if they are commonly used, and specified as such." Hopefully that clears it up.

2023-04-19 22:08 UTC, elliottower commented on _data/project_standards.yml
> +        - name: "<b>Projects should look professional and highly polished.</b> This means having a comprehensive README and documentation site, with straightforward wording which makes sense to new u
I added for example, to indicate that it wasn't the only thing that it meant: "<b>Projects should be highly polished and look professional.</b> For example, projects should have a comprehensive README and documentation site, with straightforward wording that makes sense to new users. Avoid excessive technical jargon in favor of intuitive explanations, examples and images."

2023-04-19 22:10 UTC, elliottower commented on _data/project_standards.yml
> +        - name: "<b>Projects should look professional and highly polished.</b> This means having a comprehensive README and documentation site, with straightforward wording which makes sense to new u
I wanted to include the writing bits about images and examples somewhere, but maybe those should be separate. I could add a sentence that elaborates more about the highly polished and looking professional part, but I wasn't sure what else to say. Maybe something along the lines of saying that there will be a lot of people looking at them and we want things to adhere to our maturity standards or something

2023-04-19 22:11 UTC, elliottower commented on _data/project_standards.yml
> +        - name: "<b>Projects should look professional and highly polished.</b> This means having a comprehensive README and documentation site, with straightforward wording which makes sense to new u
Which now that I think about it, the project maturity checklist should probably be on here somewhere, and be linked. I saw an issue in shimmy with it, but wasn't sure if it was just taken from overleaf or if there's a checklist somewhere else that projects should use.

2023-04-24 16:01 UTC, merged