Add Gymnasium v1.0 blog post
Farama-Foundation/farama.org pull request #90
Opened 2024-10-01 09:41 UTC by pseudo-rnd-thoughts

2024-10-04 15:13 UTC, Kallinteris-Andreas requested changes
Overall looks good

2024-10-04 15:13 UTC, Kallinteris-Andreas commented on _posts/2024-10-01-Gymnasium-v1.0.md
> +We also changed the autoreset behavior of vectorized environments. In the past, when an episode terminated (or was truncated), it would immediately reset, with the final observation being passed in t
"auto-reset behavior"

2024-10-04 15:13 UTC, Kallinteris-Andreas commented on _posts/2024-10-01-Gymnasium-v1.0.md
> +To enable a different coding paradigm and allow for easier integration into planning algorithms, Gymnasium introduces `FuncEnv`, a functional version of `Env`. This new environment type exposes funct
1) "massive"
2) "JAX"
3) "JITed"

2024-10-04 15:13 UTC, Kallinteris-Andreas commented on _posts/2024-10-01-Gymnasium-v1.0.md
> +This problem of having Gymnasium depend on a fork of a fork of the ALE meant that any changes (such as new environments) or bug fixes that occurred in the ALE were not available in Atari-Py, which in
"well-founded"

2024-10-06 16:19 UTC, pseudo-rnd-thoughts commented on _posts/2024-10-01-Gymnasium-v1.0.md
> +excerpt: ""
Thanks, added

2024-10-06 16:22 UTC, pseudo-rnd-thoughts commented on _posts/2024-10-01-Gymnasium-v1.0.md
> +To enable a different coding paradigm and allow for easier integration into planning algorithms, Gymnasium introduces `FuncEnv`, a functional version of `Env`. This new environment type exposes funct
Thanks, I'm going to keep `jitted` as this is often how is referred in the docs

2024-10-06 16:30 UTC, merged